### ISSUE TITLE
Split out ASP.NET Core hosting dependency from 2.1-dev

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-extensions-logging#102]
Although we're targeting the hosting infrastructure with `UseSerilog()` in ASP.NET Core 2, other environments that use Serilog + MEL may not want this dependency (e.g. Orleans).

Following the naming pattern used by ASP.NET Core 2, I'm working on new _Serilog.AspNetCore_ and _Serilog.AspNetCore.All_ packages here: https://github.com/nblumhardt/serilog-aspnetcore.

Once that's ready to move over into the Serilog org, we can remove the `UseSerilog()` extension and web sample from this repository.

**Comment by merbla** [comment]
Is it worth attempting to keep those meta packages in this repo and use a separate build?

**Comment by nblumhardt** [comment]
Thanks for the suggestion. I thought about it, but the effort maintaining a different build didn't seem worth it. Have had my head down, sorry I missed your comment before charging ahead :-)

https://github.com/serilog/serilog-aspnetcore

(I've left out the _All_ package for now, just needs more fiddling around.)

Tried getting the essentials into the README over there - any thoughts?

**Comment by merbla** [comment]
Looks good, do we ditch the sample from this repo in favour of that one?

**Comment by nblumhardt** [comment]
:+1: yes, going to strip this repo back a bit, PR incoming :-)
