### ISSUE TITLE
Identify gaps in the `UseSerilog()` ASP.NET Core integration experience

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-extensions-logging#103]
From #98. List to be constructed:

 - Automatic provider registration by the framework
 - ...

**Comment by Mystere** [comment]
The documentation suggests configuring Serilog in the CreateServices section, however, the newer way to do this is in the BuildWebHost configuration.

For example:

```
public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseApplicationInsights()
                .ConfigureLogging(logging =>
                    {
                        logging.AddSerilog();
                    })
                    .UseStartup<Startup>()
                .Build();
```

**Comment by nblumhardt** [comment]
The code and docs at https://github.com/serilog/serilog-aspnetcore have had a few updates since this ticket was raised; closing.

**Comment by VedantPhougat** [comment]
Install Serilog.AspNetCore package. And include it in your program file, to use `UseSerilog()`.
