### ISSUE TITLE
netcore 1.0 usage.

### ISSUE THREAD

**Issue by dazinator** [serilog/serilog-extensions-logging#109]
There doesn't appear to be an overload for `AddLogging()` that takes an `Action` as specified in the README in asp.net core 1.0.X

![image](https://user-images.githubusercontent.com/3176632/30023549-d6e4062a-9167-11e7-9d46-58b072d39968.png)

**Comment by nblumhardt** [comment]
Thanks Darrell, you're quite right - the README mentions 1.0, 1.1 and default provider integration, but only shows 2.0 default provider configuration. Will fix :+1:
