### ISSUE TITLE
How to get class + method information emitted to log

### ISSUE THREAD

**Issue by sarchibald-mdsol** [serilog/serilog-extensions-logging#110]
I'm used to using NLog, but the company at which I am working is using SeriLog. NLog has a layout render ${callsite} which will emit the class name + method name in the log automagically. 

I see that SeriLog has {SourceContext}, but that only seems to list the class name. Is there a way to get both the class name and the method name?

**Comment by nblumhardt** [comment]
Hi! We've been wary of the potential for performance issues and steered clear of this feature so far, but, it'd be interesting to try porting NLog's implementation to a Serilog `ILogEventEnricher` - perhaps something that could ship and be plugged in as an additional package? Let me know if you are keen to take a shot, happy to help out.

Cheers,
Nick

**Comment by nblumhardt** [comment]
There's now a sample enricher published for this; please see https://github.com/serilog/serilog/issues/1084 and feel free to add any feedback over there. Thanks!
