### ISSUE TITLE
Configure log level in appsettings.json?

### ISSUE THREAD

**Issue by dasjestyr** [serilog/serilog-extensions-logging#125]
So I have signalR installed, and I my logsettings in appsettings.json are as follows:

``` json
"LogLevel": {
      "Default": "Information",
      "System": "Warning",
      "Microsoft": "Information"
    }
```

However, I'm getting spammed with VRB messages from signalR and it only goes away if I remove this serilog integration. Is there some other configuration step I'm missing?

**Comment by dasjestyr** [comment]
I just realized that I should be using Serilog.AspNetCore so I swapped out for that and have the same issue. 

It looks like the SignalR team will be removing that spam, however I don't think that's the root of the problem. That log is being sent as a Trace which serilog is correctly outputting as Verbose. But if the minimum level is Information, then these shouldn't be getting through, so I'm not sure if I'm missing a configuration item somewhere.

**Comment by nblumhardt** [comment]
@dasjestyr thanks for the follow-up. Are the messages from SignalR correctly tagged with a `Microsoft.*` source context?

**Comment by dasjestyr** [comment]
I can't really tell. Do you know where I should look?

**Comment by nblumhardt** [comment]
Depends on where you're sending the events - if JSON, for example, they'll have a `SourceContext` property.

One other realisation - when you swapped to _Serilog.AspNetCore_, did you remove `ConfigureLogging()` and add `UsingSerilog()`? Otherwise these two package will behave the same way.

**Comment by nblumhardt** [comment]
Closing this one as stale, but please let us know if you need any help with it :-)

**Comment by vlixplatform** [comment]
Sure need help on this one!
