### ISSUE TITLE
Change namespace for SerilogLoggingBuilderExtensions.AddSerilog

### ISSUE THREAD

**Issue by tai-yi** [serilog/serilog-extensions-logging#134]
Please change  `SerilogLoggingBuilderExtensions`'s namespace to `Microsoft.Extensions.Logging`.
I just want add Serilog.
```
services.AddLogging(c =>
            {
                c.AddConsole();
                c.AddSerilog();
            });
```

Got too many error.
``` 
'ILogger' is an ambiguous reference between 'Microsoft.Extensions.Logging.ILogger' and 'Serilog.ILogge'
```

**Comment by nblumhardt** [comment]
Thanks for the feedback 👍 

At this stage, a namespace change would be tricky, breaking existing binaries compiled against this package. I don't think it's a change we can make in the near future, but worth us keeping in mind.

Thanks again!
