### ISSUE TITLE
Debug vs Verbose

### ISSUE THREAD

**Issue by adamhathcock** [serilog/serilog-extensions-logging#14]
I understand MF.Logging and Serilog have different priority levels but it's really bothersome to see logger.LogDebug show up as Verbose in serilog.

Is that the final word on how this should work?

**Comment by nblumhardt** [comment]
Unfortunately yes, unless we can convince the folks over at aspnet/logging to change course on that one :-)

Switching the two levels is likely to be even more confusing I'm afraid :-(

**Comment by adamhathcock** [comment]
I might make an issue on their side.

Hah, I just checked and there is a similar for NLog: https://github.com/aspnet/Logging/issues/237

Just to validate, Serilog would like Verbose to be the lowest, not Debug.  It looks like NLog wants Trace (instead of Verbose) to be the lowest and not Debug.  MF.Logging has Debug being the lowest below Verbose: https://github.com/serilog/serilog/blob/dev/src/Serilog/Events/LogEventLevel.cs

If they don't change, how awful would it be to make an optional to switch or skip the Verbose level?  I'm just trying to think of something to make it less awkward.

**Comment by nblumhardt** [comment]
Yes, all options are definitely on the table. Thanks for following up!

**Comment by nblumhardt** [comment]
This has been fixed in the dev branch of ASP.NET :-) We need to get dev on this repo lined back up with their MyGet builds...

**Comment by nblumhardt** [comment]
Done - https://www.nuget.org/packages/Serilog.Extensions.Logging/1.0.0-rc2-10096
