### ISSUE TITLE
`LoggerProviderCollection` should not be `IDisposable`

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-extensions-logging#143]
The providers within it are generally owned by the composition system, e.g. https://github.com/serilog/serilog-extensions-logging/blob/dev/samples/Sample/Program.cs#L31 - so it has no business disposing them :-)

**Comment by nblumhardt** [comment]
Second thoughts, this needs a careful look, providers may not be flushed if they're not otherwise disposed by the DI container.

**Comment by SimonCropp** [comment]
given v3 has been released. is this included in that milestone? and should the milestone be closed

**Comment by nblumhardt** [comment]
Thanks 👍
