### ISSUE TITLE
Log filtering seems to be ignored due to override

### ISSUE THREAD

**Issue by dpoole73** [serilog/serilog-extensions-logging#147]
I've been trying to use the AddSerilog() extension method to add Serilog logging in my builder but found that any filtering I apply is overridden in the extension method, for example:

```
services.AddLogging(l => l.AddFilter((cat, lev) => 
                { 
                    // Filter information logs from Sample.Program
                    if (cat.StartsWith("Sample.Program"))
                    {
                        return lev >= LogLevel.Warning;
                    }
                    // else informational only
                    return lev >= LogLevel.Information;
                })
                .AddConsole()
                );
```

then
```
    logger.LogInformation("Information");
    logger.LogWarning("Warning");
```
displays only the warning message:

```
warn: Sample.Program[0]
      Warning
```

If I add `.AddSerilog()` like this:

```
services.AddLogging(l => l.AddFilter((cat, lev) => 
                { 
                    // Filter out all EF logs to stop it being so chatty
                    if (cat.StartsWith("Sample.Program"))
                    {
                        return lev >= LogLevel.Warning;
                    }
                    // else informational only
                    return lev >= LogLevel.Information;
                })
                .AddConsole()
                .AddSerilog()
                );
```

I see both messages from the serilog logger and only the warning message from the .net logger:

```
[08:47:47 INF] Information
[08:47:49 WRN] Warning
warn: Sample.Program[0]
      Warning
```

this seems to be due to this [this line](https://github.com/serilog/serilog-extensions-logging/blob/29bdf6ca8654412f4e820203426045f397461c5c/src/Serilog.Extensions.Logging/SerilogLoggingBuilderExtensions.cs#L49) If I comment that line out then filtering works as expected.  Was this left for debugging purposes?  Should it be controlled via a parameter to the method?  It doesn't seem like it is needed since you can control filtering outside.

**Comment by nblumhardt** [comment]
Hi @dpoole73 - thanks for the note.

You can read some of the discussion regarding this in https://github.com/serilog/serilog-extensions-logging/issues/98.

The eventual result of working through this was [_Serilog.AspNetCore_](https://github.com/serilog/serilog-aspnetcore)'s `UseSerilog()` and the related instructions in that README; see alternatively [_Serilog.Extensions.Hosting_](https://github.com/serilog/serilog-extensions-hosting) if you're not in a web app.

If your app's a plain console app, then configuring everything via Serilog (sinks, levels, filters, etc.) and just using _Microsoft.Extensions.Logging_ as a logging abstraction will be a better experience. Let us know if you need more details on this.

Cheers,
Nick
