### ISSUE TITLE
Please update CHANGES.md - last updated 2016-08-03 at version 1.2

### ISSUE THREAD

**Issue by Jehoel** [serilog/serilog-extensions-logging#154]
My WebForms project currently references `Serilog.Extensions.Logging` version 2.0.4 and NuGet tells me version 3.0.1 is out - but the first digit is different - which under SemVer means it's a breaking change - which means head to the changelist!

...but the changelist https://github.com/serilog/serilog-extensions-logging/blob/dev/CHANGES.md was last updated over 3 years ago and doesn't mention any changes since version 1.2, but now we're at version 3.0.1.

**Comment by nblumhardt** [comment]
Thanks for the note :+1:. The https://github.com/serilog/serilog-extensions-logging/releases page is now the place to track per-release changes, we haven't maintained a CHANGES.md in any Serilog repo for a long while, but didn't clear out the old files as we should have).
