### ISSUE TITLE
UseSerilog implementation

### ISSUE THREAD

**Issue by dazinator** [serilog/serilog-extensions-logging#163]
Hello it's me again!

I couldn't use `UseSerilog()` in my application for reasons [delved into here](https://github.com/OV2012/Dotnettency.Samples/pull/1 ) (my application is complex using autofac and child containers, and my own library for multitenancy) - and my workaround was to do this instead:

```
               webhostBuilder.ConfigureLogging((logging) =>
                {
                    logging.ClearProviders();// clears microsoft providers registered by default like console.
                    logging.AddSerilog(Logger);
                });
```

Which works. I raise this here because I thought maybe you could simplify the UseSerilog() implementation to call this method on the host builder instead, and then you could [ditch your custom ILoggerFactory](https://github.com/serilog/serilog-extensions-logging/blob/79127bdf6e9d94a63dab60fb9aba94543903fe95/src/Serilog.Extensions.Logging/Extensions/Logging/SerilogLoggerFactory.cs) ?

**Comment by nblumhardt** [comment]
Thanks for the note! The workaround you're using is the supported one, here; we deliberately use our own `ILoggerFactory` to avoid inconsistencies/edge cases around filtering and configuration, but the Serilog provider works when the default approach isn't viable 👍
