### ISSUE TITLE
InvalidOperationException when requesting injected ILogger using Github example

### ISSUE THREAD

**Issue by audigex** [serilog/serilog-extensions-logging#172]
When using the example code from this github page and requesting ILogger as an injected dependency in the constructor, I get an InvalidOperationException

```
// Startup.cs / Startup
Log.Logger = new LoggerConfiguration()
      .Enrich.FromLogContext()
      .WriteTo.Console()
      .CreateLogger();

// Startup.cs / ConfigureServices
services.AddLogging(loggingBuilder =>
      	loggingBuilder.AddSerilog(dispose: true));

// MyClass.cs / Constructor
public MyClass(ILogger logger)
```

With the exception

```
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate....
```

If I throw an exception in MyClass, it's logged correctly by Serilog, so presumably Serilog is working as middleware, but I can't inject it in order to log messages directly: am I missing something?

I can force it to work with the following in ConfigureServices, but then I'm not injecting an ILogger interface and my code is dependent on Serilog rather than being able to inject any other logger implementing Microsoft's ILogger interface, which doesn't seem quite right?

```
services.AddSingleton(Log.Logger);
````

**Comment by sungam3r** [comment]
I think you need Serilog logger, not Microsoft. Check namespaces.

**Comment by Numpsy** [comment]
You might need that to be

```
// MyClass.cs / Constructor
public MyClass(ILogger<MyClass> logger)
```

?

**Comment by audigex** [comment]
Thanks that was the issue - I did try that previously but missed the fact I needed to also change my private field to ILogger<MyClass> too - the exception had changed but I didn’t notice

**Comment by nblumhardt** [comment]
Serilog's `ILogger` can also be injected, if you use `UseSerilog()` from _Serilog.Extensions.Hosting_, instead of `AddSerilog()`. HTH!
