### ISSUE TITLE
System.Diagnostics.Activity.Current is Null when UseSeriLog()

### ISSUE THREAD

**Issue by avireddy02** [serilog/serilog-extensions-logging#174]
In the middleware, i'm using System.Diagnostics.Activity.Current to get hold of TraceId which is null when I add .UseSerilog() to IHostBuilder.  Also i'm using AspNetCore implementation of Trace Context "System.Diagnostics.Activity.DefaultIdFormat = ActivityIdFormat.W3C;" which is new standard to log Correlation Id in Aspnetcore 3.*

Framework: AspNetCore 3.1 
Program.cs
```
       public static void Main(string[] args)
        {
            System.Diagnostics.Activity.DefaultIdFormat = ActivityIdFormat.W3C;
            CreateHostBuilder(args).Build().Run();
        }
```

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                }).UseSerilog();
    
In middleware:
System.Diagnostics.Activity.Current.TraceId.ToString()

Exception:
Object reference  not set to an instance.
because System.Diagnostics.Activity.Current is null

**Comment by nblumhardt** [comment]
Hi! To help, we'll need some idea of what the middleware looks like, where it sits in the pipeline, and what the stack trace of the exception is - thanks!

**Comment by avireddy02** [comment]
@nblumhardt I have uploaded a sample repo with middleware and serilog config [Sample Code in GitHub](https://github.com/avireddy02/Serilog.Ext.Logging.Bug.174)

**Comment by skomis-mm** [comment]
Hi @avireddy02 ,

According to the [source](https://github.com/dotnet/aspnetcore/blob/release/3.1/src/Hosting/Hosting/src/Internal/HostingApplicationDiagnostics.cs#L48), Activity starts if logging is enabled.

So in your sample you need to preconfigure Serilog logger first

**Comment by avireddy02** [comment]
@skomis-mm Will you able to point me to an example?

**Comment by skomis-mm** [comment]
@avireddy02 look [here](https://github.com/serilog/serilog-aspnetcore#instructions) for an example

**Comment by avireddy02** [comment]
@nblumhardt & @skomis-mm Above suggestion worked. Thank you!!! 🙏

**Comment by clint-mcc-cognizant** [comment]
After following the instructions [here](https://github.com/serilog/serilog-aspnetcore#instructions) - everything is logging correctly but Activity.Current still resolves to null.

I've setup the Log.Logger within the main startup, and am using 

`Host.CreateDefaultBuilder(args)
                .UseSerilog()
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    config.AddEnvironmentVariables();
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });`

In addition to setting up the logger before the HostBuilder is created. Everything logs fully as expected, but Activity is still null.

Has something changed since this was last answered/closed?

Thank you
