### ISSUE TITLE
Mention Serilog.Extensions.Hosting in the readme

### ISSUE THREAD

**Issue by BobVul** [serilog/serilog-extensions-logging#180]
Currently, the readme mentions two scenarios:

* ASP.NET Core 2.0+ => Serilog.AspNetCore
* .NET Core 1.0, 1.1 => Serilog.Extensions.Logging

It makes no mention of the best approach for .NET Core 2.x and 3.x applications that do *not* use ASP.NET. From what I can tell, Serilog.Extensions.Hosting is the recommended package in this case, but it takes some digging through issues to find; it's not listed in the Serilog.AspNetCore readme either.

Please consider including a section in the readme pointing towards to recommended approach for non-ASP .NET Core 2.x/3.x projects.

**Comment by nblumhardt** [comment]
Done - thanks!

**Comment by BobVul** [comment]
Thanks!
