### ISSUE TITLE
Consider publishing for net461 like Microsoft.Extensions.Logging does

### ISSUE THREAD

**Issue by Nefarion** [serilog/serilog-extensions-logging#196]
Microsoft.Extensions.Logging 5.* targets net461 as well.

I had to fork the repo and republish with net461, because with the current version i get a MissingMethodException on AddSerilog().

Greetings from Vienna!

**Comment by nblumhardt** [comment]
Thanks for the note. IIRC, 4.6.1 has some deployment issues for .NET Standard that don't occur in 4.6.2 - will need to go back over some history to figure out how we ended up at the current targets... :-) (and greetings from Brisbane!)

**Comment by Nefarion** [comment]
I just found this comment (https://github.com/serilog/serilog-extensions-logging/pull/191#issuecomment-865435500), i had the same problem and publishing for net461 fixed it.

**Comment by SimonCropp** [comment]
givven support for net461 [expires next month](https://en.wikipedia.org/wiki/.NET_Framework_version_history#Overview), it is trivial to update to 462 of higher, i dont think this is worth the effort

**Comment by sungam3r** [comment]
According to 
> These must match the Dependencies tab in https://www.nuget.org/packages/microsoft.extensions.logging at  the target version.

note from csproj for v7 I think this issue can be closed as not planned.
