### ISSUE TITLE
Serilog and compile-time logging source generation

### ISSUE THREAD

**Issue by sakno** [serilog/serilog-extensions-logging#197]
[Logging message generator](https://docs.microsoft.com/en-us/dotnet/core/extensions/logger-message-generator) introduced in .NET 6 is not compatible with Serilog `@` operator. Any attempt to use this operator in [LoggerMessageAttribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggermessageattribute) causes compilation error.

**Comment by nblumhardt** [comment]
Thanks for the heads-up. That's not our code - you'll need to raise this on `dotnet/runtime`. If you need any extra info though, please loop me in :-)

**Comment by nblumhardt** [comment]
CC @snakefoot, who may be interested in this from the NLog perspective.

**Comment by willbush** [comment]
https://github.com/dotnet/runtime/pull/79038 was merged. Shouldn't this be closed?
