### ISSUE TITLE
Serilog.Extensions.Logging vs Serilog.AspNetCore

### ISSUE THREAD

**Issue by sentouki** [serilog/serilog-extensions-logging#202]
I'm a little bit consfused about what to use.
Both seem to do the same, logging, into files or into console.
I'm planning to use Serilog for a Blazor Server (.NET 6) project.
For now, dumping the logs to the console should be enough but in the future I'd like to log to Seq.
Any recommendations? Thanks in advance.

**Comment by bartelink** [comment]
For questions like this, better to ask a question on stackoverflow.com - logging issues on a repo like this is not a good medium for usage questions and instead are best used for actual engineering issues related to this specific codebase.
 
In general I'd start with overviews such as https://blog.datalust.co/using-serilog-in-net-6/ and https://nblumhardt.com/2019/10/serilog-in-aspnetcore-3/
You may be able to find a good Serilog Blazor intro article that builds on that (I have not searched.)

Regarding your SO post, I'd suggest:
- Pick whether you want to use Console or Seq - no point getting two sets of answers and/or making your question confusing by bringing that into it - one question at a time.
- State your goals, your constraints etc, and what you've tried, and you should get some answers.
- If you tag it `serilog`, anyone that monitors notifications on these repos will also see it over there, and they'll be much more likely to respond (furthermore, there will be lots of people who will see the question that never traverse these repos.)
