### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by pengweiqhca** [serilog/serilog-extensions-logging#205]
[`LoggerProviderCollectionSink`](https://github.com/serilog/serilog-extensions-logging/blob/dev/src/Serilog.Extensions.Logging/Extensions/Logging/LoggerProviderCollectionSink.cs#L60) and [`EventSourceLoggerProvider`](https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.Logging.EventSource/src/EventSourceLoggerProvider.cs#L34) not cache `CreateLogger` result, lead to memory leak.
![a](https://user-images.githubusercontent.com/3982826/164956049-a66bb301-fcf5-44cd-b81c-4badfb0f3a0f.png)
![b](https://user-images.githubusercontent.com/3982826/164956151-8f7603b6-f6f8-4cc0-9d93-ad31efbcf141.png)

**Comment by nblumhardt** [comment]
Thanks for the report; this is being discussed in: https://github.com/dotnet/runtime/issues/66072
