### ISSUE TITLE
Question: Any way to add deconstruction when no at-sign is in message template?

### ISSUE THREAD

**Issue by GeraldLx** [serilog/serilog-extensions-logging#207]
The Microsoft abstractions are currently the standard for combining projects.

So in all our current projects we set up Microsoft Logging with Serilog. From a perspective of our own code there is no real benefit as we have everything in our hands. The advantage is that all 3rd party libraries also automatically log into our Seq.

The problem I have is that some libraries have hand written ToString methods for their classes generating some ugly output (of course personal taste *g*).

I would like to replace this with my custom deconstruction, but as the library is external, I cannot replace the message template by adding an @ sign.

I think the @ sign system is a nice and perfect solution from a Serilog perspective, but abstractions relying on specific implementations are not really abstractions ;)

I am not sure if this is the right place. Either we would need a way to customize the default behavior (scalar/deconstruction) for specific types in the Serilog base library or a way to transform this in the adapter.

**Comment by nblumhardt** [comment]
Hi Gerald!

`@` is part of the abstraction - it's recognized by the full-featured structured logging back-ends (Serilog and NLog), has been part of the https://messagetemplates.org spec since the beginning, and is accepted by _Microsoft.Exensions.Logging_ pretty much everywhere. Raising issues with the external libraries is the best path forward :-)

Hope this helps,
Nick

**Comment by bartelink** [comment]
>Therefore I asked if it is possible to overwrite this behavior from the outside

Have you considered asking whether the lib would consider exposing a mechanism to expose its raw data (e.g. a dictionary of values like ForContext can use) and/or use `@` ? Sounds like the sort of thing that lots of people would be interested in?

As a hack until it's done, you might be able to decorate the ILogger with a helper that inserts an `@` into the message template that the lib is passing,`

**Comment by sungam3r** [comment]
https://github.com/EasyNetQ/EasyNetQ/discussions/1484

**Comment by nblumhardt** [comment]
Closing as stale; looks like @sungam3r has helped find a solution that works with the original source library.
