### ISSUE TITLE
Upgrade codebase

### ISSUE THREAD

**Issue by sungam3r** [serilog/serilog-extensions-logging#211]
@nblumhardt Would you like a PR upgrading codebase to use the latest .NET7 SDK? 

Features:
- tests for modern TFMs
- file-scoped namespaces
- implicit usings
- switch expressions
- sample/benchmarks project for net7 instead of netcoreapp2.0/2.2

No changes in actual `Serilog.Extensions.Logging` project code and its dependencies.

**Comment by nblumhardt** [comment]
Sounds great @sungam3r

**Comment by sungam3r** [comment]
Also in #214 

- .editorconfig rules
- SourceLink support with embedded pdb
- Embedded readme for nuget.org
- NRT annotations
