### ISSUE TITLE
Serilog keeps throwing ArgumentNullException

### ISSUE THREAD

**Issue by shalabala** [serilog/serilog-extensions-logging#213]
I am using asp .net and serilog 2.10 and Microsoft.Extensions.Logging 3.1.0 but i have been able to find the source of my problem in the current sources.

My problem is that every time there is a request, an ArgumentNullExceptions appears in the project output:

```
Exception thrown: 'System.ArgumentNullException' in System.Collections.Concurrent.dll: 'Value cannot be null.'
Stack trace:
 >   at System.ThrowHelper.ThrowArgumentNullException(String name)
 ```
 I have been able to trace back the problem to the following source files:

https://github.com/serilog/serilog-extensions-logging/blob/5bd2cc04f9cf7e69dda6ae09993a8d3484daab0d/src/Serilog.Extensions.Logging/Extensions/Logging/LoggerProviderCollectionSink.cs#L60

If here categoryName is null, and the provider is Microsoft.Extensions.Logging.Console.ConsoleLoggerProvider, then it will end up in this line:
https://github.com/dotnet/runtime/blob/fb13c2cf6eaf69b53773e94674772f217fa39416/src/libraries/Microsoft.Extensions.Logging.Console/src/ConsoleLoggerProvider.cs#L158

Which will throw an ArgumentNullException:
https://github.com/microsoft/referencesource/blob/51cf7850defa8a17d815b4700b67116e3fa283c2/mscorlib/system/collections/Concurrent/ConcurrentDictionary.cs#L500

I dont know if im doing something wrong, but the cited piece of code seems to be not very well guarded against nulls, and this is a very criptic error message, that took me hours to track down, and i'mstill not sure, how to proceed.

Thanks for any help

**Comment by sungam3r** [comment]
Append `Enrich.WithSourceContext()` to your Serilog configuration.

**Comment by nblumhardt** [comment]
Sounds like a bug, thanks 👍

**Comment by shalabala** [comment]
> Append `Enrich.FromLogContext()` to your Serilog configuration.

It is already in there

**Comment by sungam3r** [comment]
Then could you debug and see the value of `categoryName`?

**Comment by shalabala** [comment]
it is null

**Comment by sungam3r** [comment]
This contradicts the fact that you have `Enrich.FromLogContext()`. Does `SourceContext` property exist inside `logEvent`?

**Comment by nblumhardt** [comment]
Not all log events will have a `SourceContext` - it's only added when the logger is created using `ForContext<T>()`.

The `Enrich.FromLogContext()` mechanism only attaches values from `LogContext.PushProperty()`.

We'll need to use a default category category name for MEL providers in these cases (e.g. `"None"`).

**Comment by sungam3r** [comment]
> Not all log events will have a SourceContext - it's only added when the logger is created using ForContext<T>()

That is when injecting generic logger.

**Comment by sungam3r** [comment]
But I understand that it's better to set default category. I can post PR. Would you like "None", "Default", "Serilog", etc?

**Comment by nblumhardt** [comment]
This case is going in the opposite direction - when we log through Serilog, but write back to MEL providers, so the source is not necessarily a generic `ILogger`.

A PR would be welcome, turnaround is a bit slow right now but I'm getting some time back from other projects so should be able to check it out before tooooooo long :-)
