### ISSUE TITLE
Unit tests fail when run for .Net Framework

### ISSUE THREAD

**Issue by schokee** [serilog/serilog-extensions-logging#236]
Appears to be a JIT error in `Serilog.Extensions.Logging.SerilogLogger.Log` when invoking `PrepareWrite`:
```
System.MissingMethodException : Method not found: 'Void Serilog.Events.LogEvent..ctor(System.DateTimeOffset, Serilog.Events.LogEventLevel, System.Exception, Serilog.Events.MessageTemplate, System.Collections.Generic.IEnumerable``1<Serilog.Events.LogEventProperty>, System.Diagnostics.ActivityTraceId, System.Diagnostics.ActivitySpanId)'.
```

**Comment by Numpsy** [comment]
Which version of .NET Framework? (the CI builds seem to be passing against 4.8)

**Comment by schokee** [comment]
Thanks for your prompt reply. Looking at the loaded modules (via the Modules window in VS) I can see that an older version of Serilog (v2.0, targeting .Net 4.6) is being loaded from the GAC. This would explain the JIT error in my environment, so this can be closed.
