### ISSUE TITLE
SerilogLogger.cs: PrepareWrite Method not found Serilog.Events.LogEvent..ctor

### ISSUE THREAD

**Issue by davidcaldas** [serilog/serilog-extensions-logging#238]
Hi!

I have an issue while using the package in a simple console application with .NET Framework 4.7.2. 
The problem is in the SerilogLogger.cs file in the method PrepareWrite.

When I try logging I get this error:
`Failed to write event through SerilogLogger: 
System.MissingMethodException: Method not found: 'Void Serilog.Events.LogEvent..ctor(System.DateTimeOffset, Serilog.Events.LogEventLevel, System.Exception, Serilog.Events.MessageTemplate, System.Collections.Generic.IEnumerable`1<Serilog.Events.LogEventProperty>, System.Diagnostics.ActivityTraceId, System.Diagnostics.ActivitySpanId)'.
   at Serilog.Extensions.Logging.SerilogLogger.PrepareWrite[TState](LogEventLevel level, EventId eventId, TState state, Exception exception, Func`3 formatter).
`

Unit tests are failing in .NET48
![image](https://github.com/serilog/serilog-extensions-logging/assets/39414148/4f16cc2a-69fa-4feb-a16e-371b4dc51ac5)

**Comment by nblumhardt** [comment]
Hi @davidcaldas; looks like you have a mix of Serilog versions in there. Adding a direct reference to the Serilog package, v3.1.1, should sort it out.

**Comment by davidcaldas** [comment]
Thank @nblumhardt for the help. The version 2.1 of GAC was being loaded instead of the local 3.1..
