### ISSUE TITLE
Avoid boxing of TState

### ISSUE THREAD

**Issue by jods4** [serilog/serilog-extensions-logging#241]
`[LoggerMessage]` generate a `struct` state, in an attempt to reduce allocations.

For this to be meaningful, state should not be boxed, but it is in `AsLoggableValue`:

https://github.com/serilog/serilog-extensions-logging/blob/dev/src/Serilog.Extensions.Logging/Extensions/Logging/SerilogLogger.cs#L168-L174

```cs
// Current version:
static object? AsLoggableValue<TState>(TState state, Func<TState, Exception?, string>? formatter)
{
    object? stateObj = state;  // <- always boxing!!
    if (formatter != null)
        stateObj = formatter(state, null);
    return stateObj;
}

// Suggested:
static object? AsLoggableValue<TState>(TState state, Func<TState, Exception?, string>? formatter)
{
    object? stateObj = null;
    if (formatter != null)
        stateObj = formatter(state, null);
    return stateObj ?? state; // <- boxed only when needed
}
```

Note that in the case of `[LoggerMessage]` a `formatter` is always provided (to create the formatted string without boxing of its parameters), so `stateObj` will never be null and `state` will not be boxed.

For the curious mind, in `PrepareWrite()` the code `if (state is IEnumerable<..> structure)` does not result in boxing because JIT compiles each struct `TState` separately and statically optimizes these conditions and interfaces, as can be seen in this disassembly (`call S.GetEnumerator`): 
https://sharplab.io/#v2:EYLgtghglgdgNAFxBAzmAPgAQEwEYCwAUJgAwAEmuAdAMID2ANgwKYDGCUdMKA3EaRVwAWPoSIoEAJwCu7MgGUyIQQGYAPAGlmATwBqEBtOYAFaJLWUScMnWAArNggB8TogG8iZLxRVkAkgCiMNJgzJIQCHTmWnoGRqZQ5pbWtg7sLmQA4swIQSFhEVEAFACUnt4ehN7VZAgAFpJ0AO5kMMwtAHJ0CH5gAA4soTAIzAAmAQAerMx9HFylotUAvkTlXoHBoeGRkqpU2bmbBTula2SVNd71jS1tnd29A8xDI+NTM3MwC2crhL/8vhwZBo5zOAG15HUIJI+gAZCDAKgAJWkwygoSoACkoAhsm1JFBWEUENo+sw6AAzIryEolAC6Z0wgNwADYKEIyABZNQAFScRR5ZAmJVBVRqUApZCKEzIUBQqk0On0hhMZgsuCsNnsjgyzDKYuqF0u3gpUWYEFYdSlADdoWQANbWvqymBkPVnS5G401SgATiKjr6VBiJUW3rIv0uke8vyWQA==

**Comment by jods4** [comment]
BTW: it would be nice to have similar fast logging when using Serilog natively!

- MS code generator only targets `M.E.L.ILogger`, we'd need a generator whose template targets `Serilog.ILogger`. 
Source code is here: https://github.com/tkrafael/dotnet-runtime/tree/693620ed1425182d1f388f51f06fa18fb6b7e142/src/libraries/Microsoft.Extensions.Logging.Abstractions/gen
Basically only `GenLogMethod` needs to be tweaked, or even crazier idea: just depend on MS package and search and replace in the generated C# source (at first glance `ILogger` and `LogLevel` would need substitution).

- Code that writes a `struct` + `formatter` efficiently would need to be moved from `Serilog.Extensions.Logging` into `Serilog` core.

**Comment by nblumhardt** [comment]
Thanks for all the thoughts and suggestions @jods4!

Anyone keen to investigate/PR any of these? 😎

**Comment by jods4** [comment]
@nblumhardt The first changes are so trivial... here you go: #242

I should have opened a different issue for having performant code generator that works with `Serilog.Log`.
That's a whole lot more complicated, cannot be closed as quickly 😆

**Comment by jods4** [comment]
Nothing is ever trivial 🤣
Turns out `StartsWith(char)` was not part of .net fx of good ole time, so I reverted.

Could have gone creative with `str is ['@', ..]`, turns out that as optimal as it gets. Felt excessive, though 😏

**Comment by nblumhardt** [comment]
Thanks again, keen to keep chipping away at these kinds of things, nice to see small gains add up over time :-)
