### ISSUE TITLE
Update README to replace UseSerilog with AddSerilog

### ISSUE THREAD

**Issue by brental** [serilog/serilog-extensions-logging#257]
As part of [this commit](https://github.com/serilog/serilog-aspnetcore/commit/92bc15aa27f925bb590ad7940f0272013fd2ead3) in the Serilog.AspNetCore repo the guidance for using Serilog with ASP.NET Core was changed from using builder.Host.UseSerilog to using builder.Services.AddSerilog

The README in this repo still suggests using Serilog.AspNetCore with UseSerilog so it should probably be updated to suggest using Serilog.AspNetCore with AddSerilog for ASP.NET Core. See this section:
https://github.com/serilog/serilog-extensions-logging/tree/main?tab=readme-ov-file#aspnet-core-instructions

The README also suggests using Serilog.Extensions.Hosting with UseSerilog for non-web .NET Core so it should probably be updated to suggest using Serilog.Extensions.Hosting with AddSerilog for non-web .NET Core. See this section:
https://github.com/serilog/serilog-extensions-logging/tree/main?tab=readme-ov-file#non-web-net-core-instructions

**Comment by nblumhardt** [comment]
Makes sense, thanks :+1:

**Comment by JustinGrote** [comment]
Indeed, I was very confused being new to this :)

**Comment by brental** [comment]
@nblumhardt I have created #265 to address this.
