### ISSUE TITLE
Cannot add to a Web Api project

### ISSUE THREAD

**Issue by anthonymiller-simple** [serilog/serilog-extensions-logging#26]
I've tried many different version of the .net framework, 4.5.1, 4.5.2, 4.6, 4.6.1 and fails to install. With the same error.

PM> Install-Package Serilog.Framework.Logging -Pre
Attempting to gather dependencies information for package 'Serilog.Framework.Logging.1.0.0-rc1-final-10083' with respect to project 'WebApplication2', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'Serilog.Framework.Logging.1.0.0-rc1-final-10083' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Serilog.Framework.Logging.1.0.0-rc1-final-10083'
Resolved actions to install package 'Serilog.Framework.Logging.1.0.0-rc1-final-10083'
Adding package 'Serilog.Framework.Logging.1.0.0-rc1-final-10083' to folder 'C:\Users\anthony.miller\documents\visual studio 2015\Projects\WebApplication2\packages'
Added package 'Serilog.Framework.Logging.1.0.0-rc1-final-10083' to folder 'C:\Users\anthony.miller\documents\visual studio 2015\Projects\WebApplication2\packages'
Install failed. Rolling back...
Package 'Serilog.Framework.Logging.1.0.0-rc1-final-10083 : Microsoft.Extensions.Logging [1.0.0-rc1-final, ), Serilog [2.0.0-beta-423, )' does not exist in project 'WebApplication2'
Removing package 'Serilog.Framework.Logging.1.0.0-rc1-final-10083 : Microsoft.Extensions.Logging [1.0.0-rc1-final, ), Serilog [2.0.0-beta-423, )' from folder 'C:\Users\anthony.miller\documents\visual studio 2015\Projects\WebApplication2\packages'
Removed package 'Serilog.Framework.Logging.1.0.0-rc1-final-10083 : Microsoft.Extensions.Logging [1.0.0-rc1-final, ), Serilog [2.0.0-beta-423, )' from folder 'C:\Users\anthony.miller\documents\visual studio 2015\Projects\WebApplication2\packages'
Install-Package : Failed to add reference to 'System.Runtime'. Please make sure that it is in the Global Assembly Cache.
At line:1 char:1
+ Install-Package Serilog.Framework.Logging -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Sometimes it states that System.Collections.Concurrent is not in the GAC.

**Comment by nblumhardt** [comment]
Hi Anthony - thank you for the report!

I can successfully install into .NET 4.6:

```
PM> install-package serilog.extensions.logging -pre
Attempting to gather dependencies information for package 'serilog.extensions.logging.1.0.0-rc1-final-10092' with respect to project 'ConsoleApplication12', targeting '.NETFramework,Version=v4.6'
Attempting to resolve dependencies for package 'serilog.extensions.logging.1.0.0-rc1-final-10092' with DependencyBehavior 'Lowest'
Resolving actions to install package 'serilog.extensions.logging.1.0.0-rc1-final-10092'
Resolved actions to install package 'serilog.extensions.logging.1.0.0-rc1-final-10092'
Adding package 'Microsoft.Extensions.DependencyInjection.Abstractions.1.0.0-rc1-final' to folder 'c:\development\Temp\ConsoleApplication12\packages'
Added package 'Microsoft.Extensions.DependencyInjection.Abstractions.1.0.0-rc1-final' to folder 'c:\development\Temp\ConsoleApplication12\packages'
Added package 'Microsoft.Extensions.DependencyInjection.Abstractions.1.0.0-rc1-final' to 'packages.config'
Successfully installed 'Microsoft.Extensions.DependencyInjection.Abstractions 1.0.0-rc1-final' to ConsoleApplication12
Adding package 'Microsoft.Extensions.Logging.Abstractions.1.0.0-rc1-final' to folder 'c:\development\Temp\ConsoleApplication12\packages'
Added package 'Microsoft.Extensions.Logging.Abstractions.1.0.0-rc1-final' to folder 'c:\development\Temp\ConsoleApplication12\packages'
Added package 'Microsoft.Extensions.Logging.Abstractions.1.0.0-rc1-final' to 'packages.config'
Successfully installed 'Microsoft.Extensions.Logging.Abstractions 1.0.0-rc1-final' to ConsoleApplication12
Adding package 'Microsoft.Extensions.Logging.1.0.0-rc1-final' to folder 'c:\development\Temp\ConsoleApplication12\packages'
Added package 'Microsoft.Extensions.Logging.1.0.0-rc1-final' to folder 'c:\development\Temp\ConsoleApplication12\packages'
Added package 'Microsoft.Extensions.Logging.1.0.0-rc1-final' to 'packages.config'
Successfully installed 'Microsoft.Extensions.Logging 1.0.0-rc1-final' to ConsoleApplication12
Adding package 'Serilog.2.0.0-beta-465' to folder 'c:\development\Temp\ConsoleApplication12\packages'
Added package 'Serilog.2.0.0-beta-465' to folder 'c:\development\Temp\ConsoleApplication12\packages'
Added package 'Serilog.2.0.0-beta-465' to 'packages.config'
Successfully installed 'Serilog 2.0.0-beta-465' to ConsoleApplication12
Adding package 'Serilog.Extensions.Logging.1.0.0-rc1-final-10092' to folder 'c:\development\Temp\ConsoleApplication12\packages'
Added package 'Serilog.Extensions.Logging.1.0.0-rc1-final-10092' to folder 'c:\development\Temp\ConsoleApplication12\packages'
Added package 'Serilog.Extensions.Logging.1.0.0-rc1-final-10092' to 'packages.config'
Successfully installed 'Serilog.Extensions.Logging 1.0.0-rc1-final-10092' to ConsoleApplication12
PM> 
```

Is it possible you need to install VS2015 Update 1, or updated DNX tooling from ASP.NET?

HTH!
Nick

**Comment by nblumhardt** [comment]
(Just noticed I'm ending up with `-10092` which is a bit later than the version printed in your package manager output - could that help?)

**Comment by anthonymiller-simple** [comment]
The package installs fine into a console application, but not into an ASP.NET 4.5.2 application. This is not ASP.NET DNX application.

I have all the latest VS2015 updates installed. I will try again to verify the install.

**Comment by nblumhardt** [comment]
Ah - do you mean you're using the current ASP.NET, not the (upcoming) ASP.NET Core/ASP.NET 5? This package only supports the unreleased "next" version of ASP.NET.

If you are targeting vNext, would you be able to post your `project.json` file, and/or upload a zipped minimal repro? Thanks!
