### ISSUE TITLE
LogFormatter

### ISSUE THREAD

**Issue by nicolasr75** [serilog/serilog-extensions-logging#29]
I am trying to change it for compatibility with my RC2 project. One thing I can not resolve is, where does LogFormatter in this line come from:
https://github.com/serilog/serilog-extensions-logging/blob/393128db0b9cdd73aa66239b3c124b2d2d71147f/src/Serilog.Extensions.Logging/Extensions/Logging/SerilogLogger.cs#L62

The compiler complains
`The name 'LogFormatter' does not exist in the current context [netcoreapp1.0]`

Thanks for any help. Nicolas

**Comment by nblumhardt** [comment]
Hi Nicolas - not sure where it has gone in RC2; in RC1 it was provided by _m.e.Logging_. May be one to check the Logging repo's commit history for. We'll be porting soon so very interested to hear what you find! :-)

**Comment by nicolasr75** [comment]
Thanks. For the moment I have simply commented it out and it compiles and works now, at least in my limited demo app. I have not spent enough time with it and am not enough an expert to judge if my port is correct or 'optimal'. If you are still interested, I could send you the code.

**Comment by nblumhardt** [comment]
Thanks for the update. I can have a look into this when we make the port; if you're unblocked let's call this "done" for now :-)
