### ISSUE TITLE
.NET Core RC2 net451 monikor isn't supported

### ISSUE THREAD

**Issue by janpieterz** [serilog/serilog-extensions-logging#31]
My project runs on core but the net451 framework. 
```
Package Serilog.Extensions.Logging 1.0.0-rc2-10096 is not compatible with net451 (.NETFramework,Version=v4.5.1). Package Serilog.Extensions.Logging 1.0.0-rc2-10096 supports: netstandard1.3 (.NETStandard,Version=v1.3)
```
It might be me doing something dumb, I have to admit I'm not 100% sure I'm doing the transformation correctly with all the name changes. All other packages (Autofac and NServiceBus for example) work fine).

**Comment by janpieterz** [comment]
Changing my monikor to net46 works. Seems a bit odd since all of the AspNetCore libraries work in 451 and the previous version did as well, but doesn't matter that much for my deployment.

**Comment by nblumhardt** [comment]
Thanks for the report. I didn't realise the templates still generate projects targeting 451 - my test app was from the .NET Core template so didn't show this up as an issue. I think we need to accommodate it if the experience out of the box is compromised.
