### ISSUE TITLE
EventId is serialized as string "Microsoft.Extensions.Logging.EventId"

### ISSUE THREAD

**Issue by dsplaisted** [serilog/serilog-extensions-logging#33]
[Microsoft.Extensions.Logging.EventId](https://github.com/aspnet/Logging/blob/8a7ffd980af4686f7c3055b21178f8a686c40c58/src/Microsoft.Extensions.Logging.Abstractions/EventId.cs) has an Id and optionally a Name, but no override for ToString().  So [when it's added to the Serilog logging context](https://github.com/serilog/serilog-extensions-logging/blob/00bf2a3a0e21a7994abc44b159a4913370054085/src/Serilog.Extensions.Logging/Extensions/Logging/SerilogLogger.cs#L103), the value ends up being simply the type FullName.

To fix this, a custom destructurer for the EventId could be added, or the call to ForContext could explicitly pass in the Id and/or the Name.

**Comment by nblumhardt** [comment]
Thanks for the report, looking at this now.

Adding an EventId with Id and Name fields seems to be the highest-fidelity option, but it's a bit nasty to look at. Making EventId a numeric property (if not zero) and adding EventName if that part is non-null makes for nicer events, but feels like a more "opinionated" rendering.

I guess if the design of the framework calls for structured event ids we should follow that here, so I'll PR up the first option.

Cheers!

**Comment by ShadowDancer** [comment]
@nblumhardt How can I put Id part of Event structure in template? Doc seems to be silent about that?

**Comment by nblumhardt** [comment]
`{Event}` is the only option currently I'm afraid. The `AddFile()` method I posted a link to previously will do something a little more interesting/useful here.
