### ISSUE TITLE
Unable to reference Serilog in Full .NET Framework project

### ISSUE THREAD

**Issue by jamestoyer** [serilog/serilog-extensions-logging#38]
I'm working on a full .NET Framework Windows Service and trying to reference the SeriLog extension. When I do I get the following error:

```
Failed to add reference to 'System.Runtime'. Please make sure that it is in the Global Assembly Cache.
```

I believe it may be because of the following in the `project.json` file of this repo.

```
"net4.5": {
  "frameworkAssemblies": {
    "System.Runtime": ""
  }
}
```

If you add `System.Runtime` as a straight dependency instead of as a `frameworkAssemblies` entry this should then work as expected

**Comment by nblumhardt** [comment]
Thanks for the report James. After some trial and error, I've managed to get this building with a root dependency of:

```json
    "System.Runtime": "4.1.0-rc2-24027"
```

But, we end up with a warning:

```
Compiling Serilog.Extensions.Logging for .NETFramework,Version=v4.5
C:\Development\Open Source\nblumhardt\serilog-extensions-logging\src\Serilog.Extensions.Logging\project.json(14,40): warning NU1007: Dependency specified was System.Runtime >= 4.1.0-rc2-24027 but ended up with System.Runtime 4.0.0.0.
```

Unfortunately, pretty much any other permutation fails to build entirely, including setting an explicit 4.0.0 version dependency in the .NET 4 project.

Do you have any insights into this?

**Comment by nblumhardt** [comment]
Figured this out; easy fix; will merge the PR now.

**Comment by jamestoyer** [comment]
@nblumhardt Awesome. I've also just tested it out in my service and it works as expected :smiley:
