### ISSUE TITLE
Make SerilogLogger type public

### ISSUE THREAD

**Issue by victorhurdugaci** [serilog/serilog-extensions-logging#45]
Since the only public type in this package is the extension methods of the logger factory, if you want to create a logger instance, you always have to go through the factory.

For [the WebApps logger](https://github.com/aspnet/Logging/pull/468), we just need an instance of the serilog logger, but that forces us to create an factory before we can create the logger. It would be useful to have that type public so we can instantiate it directly.

**Comment by nblumhardt** [comment]
Thanks for the feedback Victor, sounds fine. I can make this change in the next day or two, or happy to accept a PR if you can send one.

**Comment by merbla** [comment]
@nblumhardt we will have to open up `SerilogLoggerProvider` & `SerilogLoggerScope` in addition to `SerilogLogger`. 

Not sure if that is the intent.

**Comment by nblumhardt** [comment]
Released in 1.2.0
