### ISSUE TITLE
How to disable default logging?

### ISSUE THREAD

**Issue by Hossrod** [serilog/serilog-extensions-logging#49]
Sorry if this is not the correct place to address this (if not, let me know where I should go). Also, I'm new to .NET Core, Web API, etc.

I setup the logger and its working, however there seems to be some default logging events coming from Core/WebAPI/etc. that I would like to disable. Essentially, the only logging I want to see is when I explicitly log (such as `_logger.LogError()`).

```csharp
public Startup(IHostingEnvironment env)
{
    Log.Logger = new LoggerConfiguration()
        .Enrich.FromLogContext()
        .WriteTo.LiterateConsole()
        .CreateLogger();
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
{
    loggerFactory.AddSerilog();
    app.UseMvc();
}
```

Without any other logging code, console is showing (this is what I don't want)...
```
[09:59:47 INF] Request starting HTTP/1.1 GET http://localhost:5000/api/values
[09:59:47 INF] Executing action method TodoAPI.Controllers.ValuesController.Get (TodoAPI) with arguments (null) - ModelState is Valid
[09:59:47 INF] Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
[09:59:48 INF] Executed action TodoAPI.Controllers.ValuesController.Get (TodoAPI) in 280.4201ms
[09:59:48 INF] Request finished in 599.358ms 200 application/json; charset=utf-8
```

Thanks for any help!

**Comment by nblumhardt** [comment]
Hi @Hossrod - you can use [MinimumLevel.Override](https://nblumhardt.com/2016/07/serilog-2-minimumlevel-override/) for this:

```csharp
    Log.Logger = new LoggerConfiguration()
        .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
        .Enrich.FromLogContext()
        .WriteTo.LiterateConsole()
        .CreateLogger();
```

**Comment by Hossrod** [comment]
Thanks @nblumhardt ! That worked great.

I also took a look at the link you provided, from it, I discovered the ability to configure this in the `appsetting.json` file. The link to `Serilog.Extensions.Configuration` was **404** however. I googled and found the below which seems to be what the link should be pointing too. Anyways, I followed it and got the Override stuff defined in the settings file and working.

https://github.com/skomis-mm/serilog-settings-configuration

Thanks again!

**Comment by nblumhardt** [comment]
Thanks for letting me know about the broken link; just pushed a fix :+1:

**Comment by MichaCo** [comment]
@nblumhardt 
Not sure if that's the best place to ask or if that is a bug related to MS Logging or general or actual intended (let me know)
I'm using Microsoft.Extensions.Logging with 
`.AddSerilog(new LoggerConfiguration().WriteTo.LiterateConsole().CreateLogger())`
for example.
per default, MinimumLoglevel ist set to Information.
For some reason though, any log message lower than Information now gets logged as information.
Like I'm logging some Trace messages and those now show up as INF messages in the console.
Is that intended? Seems a little bit odd.
Same happens using other sinks, so it seems to be unrelated to those at least.

Funny enough, the moment I put ANY override into the configuration, like 
`.MinimumLevel.Override("Microsoft", Serilog.Events.LogEventLevel.Error)`
It starts behaving as expected and filters trace messages from other namespaces as normal...
