### ISSUE TITLE
Attach hierarchical scope to log events

### ISSUE THREAD

**Issue by nblumhardt** [serilog/serilog-extensions-logging#50]
Currently, `BeginScope()` will cause any properties on the `state` object to be attached to resulting events:

https://github.com/serilog/serilog-extensions-logging/blob/dev/src/Serilog.Extensions.Logging/Extensions/Logging/SerilogLoggerScope.cs#L53

and:

https://github.com/serilog/serilog-extensions-logging/blob/dev/src/Serilog.Extensions.Logging/Extensions/Logging/SerilogLoggerProvider.cs#L61

However, it's also possible to use string "names" with scopes, and in that case some form of scope path should be attached to the event. For example:

``` csharp
using (log.BeginScope("A"))
{
    using (log.BeginScope("B")
    {
        log.LogInformation("Hello");
    }
}
```

produces a scope like `"A -> B"` in the default console logger output.

Serilog might attach these as a `Sequence` property, e.g. (in JSON rendering) `"Scope": ["A", "B"]`.

**Comment by nblumhardt** [comment]
From #8

**Comment by cilerler** [comment]
# REF [Initial discussion](http://docs.getseq.net/v3/discuss/5824ef39c8bab00f00d33e73)

Thank you, once I added `.ToString()` and it did work as expected.

> so it became `Thread.CurrentThread.ManagedThreadId.ToString()`

and result became

```
Scope     ["7", "2016-11-14T13:46:46 #1"]
```

which is exactly what I was looking for. Thank you again!

I also I tested to use the way in your sample it didn't place those 2 fields in Scope array instead added as extra fields which is also nice for the filter purpose. But I would prefer to have those as separated values and in the scope.

```
Counter  4
Scope    ["2016-11-14T13:51:23 #4"]
ThreadId 7
```

Now, is there a way to filter **Scope** array based on its values? I can filter it with `Has(Scope)` but it doesn't enough to do proper diagnostic. Simply I would like to write a query in _Seq_ as "Get all records which has `2016-11-14T13:46:46 #1` in the Scope array."

I just added additional test cases and it looks like if I write it like below

```csharp
var threadId = Thread.CurrentThread.ManagedThreadId;
var counter = 3;
using (Logger.BeginScope("Test {counter} # {threadId} ", threadId, counter) 
{ 
    //...
}
```

it appears on console as

```
=> Test 7 # 3
In
```

where it appears in _Seq_ as
```
In
counter     7
threadId    3
```

So scope does not appear even when it is text. Please let me know if you would like me to proceed further testing.

**Comment by nblumhardt** [comment]
Thanks for the feedback @cilerler. I am going to take another look at this code and see if I can come up with a consistent way to cover all cases/types.

The problem with `BeginScope("Test {counter} # {threadId} ", threadId, counter)` is that this comes through as a `FormattedLogValues` object, which is `IEnumerable<KeyValuePair<string,object>>`. In this case I think it would make sense to include the formatted text in the scope hierarchy, _as well as_ the individual property values in the event 👍

**Comment by nblumhardt** [comment]
Updated the PR so that more cases are handled.

**Comment by cilerler** [comment]
You are amazingly fast! 😎 Thank you!
