### ISSUE TITLE
Is It Possible to Reduce LogLevel For Controller Actions?

### ISSUE THREAD

**Issue by RehanSaeed** [serilog/serilog-extensions-logging#52]
I have an action that returns the status of my API which is polled by my load balancer very frequently. Is it possible to reduce the log level specifically for this action? If so, how could this be done?

**Comment by RehanSaeed** [comment]
I can use Override https://github.com/serilog/serilog/issues/754

**Comment by nblumhardt** [comment]
Great! :+1:
