### ISSUE TITLE
Doesn't show in Visual Studio Output Pane

### ISSUE THREAD

**Issue by Sean-Brown** [serilog/serilog-extensions-logging#53]
I followed the instructions and I still cannot get any log messages to display in Visual Studio's Output Pane. 
![startup](https://cloud.githubusercontent.com/assets/1503131/19810967/7fc0f1e6-9cfd-11e6-824f-b45d17db0286.PNG)
![appconfig](https://cloud.githubusercontent.com/assets/1503131/19810973/8a5e8410-9cfd-11e6-9a21-fa3c0a1cd9e8.PNG)

I added logging messages to one of my controllers. The default logger shows up just as expected, but Serilog doesn't show any output.
![incontroller](https://cloud.githubusercontent.com/assets/1503131/19811007/a8f40f9e-9cfd-11e6-884d-5b9c07bb2e34.PNG)

This is all that is displayed in output when I run the application and hit the controller:
![output](https://cloud.githubusercontent.com/assets/1503131/19811079/f27d706a-9cfd-11e6-9fda-6427f45e5999.PNG)

**Comment by Sean-Brown** [comment]
The dependencies installed in the project are:

    "Serilog": "2.3.0",
    "Serilog.Sinks.Literate": "2.0.0",
    "Serilog.Sinks.RollingFile": "3.2.0",
    "Serilog.Extensions.Logging": "1.2.0"

**Comment by nblumhardt** [comment]
Hi Sean,

The output showing in VS is from the `loggerFactory.AddDebug()` logger, not the console one. Neither the _Microsoft.Extensions.Logging.Console_ nor Serilog's console sinks will show in VS output (they go to `System.Console.Out`).

To get output in the debug window with Serilog you can use the package _Serilog.Sinks.Trace_ and `WriteTo.Trace()` - does this work for you?

Cheers!

**Comment by Sean-Brown** [comment]
Yeah that is working for me, thank you

**Comment by nblumhardt** [comment]
Great, thanks for the follow-up 👍
