### ISSUE TITLE
Please change "Microsoft.Framework.Logging" to "Microsoft.Extensions.Logging"

### ISSUE THREAD

**Issue by RickyLin** [serilog/serilog-extensions-logging#54]
![screen shot 2016-11-09 at 2 45 13 pm](https://cloud.githubusercontent.com/assets/1393989/20129558/943c0a2e-a68b-11e6-8eac-016071b0218e.png)

This is a trivial issue, but confused me when I read the page at first. I thought this repo is abandoned because of the incorrect name `Microsoft.Framework.Logging`, then I realized it's not when I read the README.

Could you guys fix this issue?

Thanks.

**Comment by merbla** [comment]
Thanks for the heads up @RickyLin!
