### ISSUE TITLE
Treat Scopes as FromContext()

### ISSUE THREAD

**Issue by cilerler** [serilog/serilog-extensions-logging#56]
It looks like `.FromContext()` is almost same as **Scopes**.  If those can be tied directly then no need to implement dependency to Serilog on classes which is a perfect reason to try/switch serilog since it will not add additional overhead to the classes as external dependency.

**Comment by nblumhardt** [comment]
Thanks @cilerler. #50 will make some advances covering this, I think this can be considered a duplicate 👍
