### ISSUE TITLE
Allow configuration using LogLevel similar to ms loggers

### ISSUE THREAD

**Issue by ShadowDancer** [serilog/serilog-extensions-logging#64]
Default aspnet logger allows me to throw at it variables from config file like:
```
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  }
```
Looks like it is impossible in serilog. My use case is that I am using serilog only for rolling file, while default console and debug loggers are running through built in loggers.
What log level property does (I think) - it limits sink level based on "SourceContext" property (I'm, not sure though).

Should there be additional overload on AddSerilog using IConfiguration and doing this?

**Comment by nblumhardt** [comment]
Howdy! You're looking for _Serilog.Settings.Configuration_: https://github.com/serilog/serilog-settings-configuration#level-overrides

If you're just after rolling file logging, also see: https://github.com/serilog/serilog-extensions-logging-file - this wraps everything up into one `AddFile()` call.

**Comment by ShadowDancer** [comment]
Close, but not really - I am looking to swap file output formatter from default to serilog, without swapping configuration format.

General idea is to take default log config format (like in first post), translate it to Serilog format and configure logger with it. If you like this idea I could program it.

To better picture the situation:
appsetings.json:
```
{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Verbose",
      "System": "Information",
      "Microsoft": "Information"
    }
  }
}
```
Program.cs:
```
 new WebHostBuilder()
                .ConfigureLogging(factory =>
                {
                    var logConfig = appConfiguration.GetSection("Logging");
                    factory.AddDebug();
                    factory.AddConsole(logConfig);
                    factory.AddFile(logConfig); // - serilog
                    factory.AddOtherLoggerThatUsesAspNetConfig(logConfig);
                })
                .Yaddayaddayadda();
```

**Comment by nblumhardt** [comment]
Hi - check out Serilog.Extensions.Logging.File, this does exactly what you're asking.

Cheers!
