### ISSUE TITLE
Can't figure out BeginScope?

### ISSUE THREAD

**Issue by Capsup** [serilog/serilog-extensions-logging#65]
Hi,

I'm having issues with the extension in a .Net Core Console Application, where I can't get the BeginScope function to do anything when using the Serilog extension.

I'm creating the logger like so:
```csharp
Log.Logger = new LoggerConfiguration().Enrich.FromLogContext().WriteTo.LiterateConsole().CreateLogger();
```

And using the logger like so (as per #50 ):
```csharp
var logger = new LoggerFactory().AddSerilog().CreateLogger(type)
var counter = 1;
var threadid = 2;
using( logger.BeginScope( "Test {counter} # {threadid}", counter, threadid ) )
{
    foreach( var registeredMethod in registeredMethods )
    {
        logger.LogInformation( "test | {0}", "abc" );
    }
}
```

However, I can't seem to get the scope to print anything at all to the console (nor using the flatfile extension):
[image](http://i.imgur.com/eQ2AVMk.png)

What am I doing wrong here?

**Comment by nblumhardt** [comment]
Howdy! To add any output to the console you'll need to specify an `outputTemplate` argument to `LiterateConsole()`:

```csharp
    .WriteTo.LiterateConsole(outputTemplate:
        "{Timestamp:o} [{Level:u3}] {Scope} {Message}{NewLine}{Exception}")
```

The `Scope` property will show if there are text scope names like yours above; alternatively you can use `{threadId}` and so-on to show individual values.

Check out: https://nblumhardt.com/2016/11/ilogger-beginscope/

Thread ids are probably better added with: https://github.com/serilog/serilog-enrichers-thread

HTH!

**Comment by Capsup** [comment]
Thanks alot. I'm sorry it took me this long to respond, but yes, you're right, I did notice that outputTemplate but didn't consider that it had something to do with it. Thanks alot for your help.

**Comment by Porges** [comment]
Just ran into this myself. It's a little unexpected that the default behaviour doesn't include `{Scope}` anywhere. Would it make sense to include it?

**Comment by nblumhardt** [comment]
@Porges thanks for the feedback.

The [Serilog.Extensions.Logging.File](https://github.com/serilog/serilog-extensions-logging-file) does, because it assumes MEL is on the front-end, but other parts of Serilog are independent of MEL and so scope doesn't really make sense for them.

In the future, more packages like the aforementioned one might help simplify the experience, but we're still in the exploratory phase.

**Comment by Porges** [comment]
@nblumhardt That makes sense, thanks 👍
