### ISSUE TITLE
Log method that allows lazily evalution of (Func<string>)

### ISSUE THREAD

**Issue by am11** [serilog/serilog-extensions-logging#66]
Howdy,

Is it possible to achieve something like this OOTB: `_logger.LogInformation(() => $"Complex computed result just before doing something else was: {DoTheMath}")`; where `DoTheMath` is potentially an expensive call, which we don't want to make when logging only the messages with high severity (criticals/fatals)?

If there is, can you please point me to a self-contained sample? 8-)

If not, any ideas how should I go about creating another wrapper over serilog-extensions-logging, that can fit into ASP.NET logging abstractions pipeline (without altering their default DI mechanics)?

Thanks!

**Comment by nblumhardt** [comment]
Hi @am11 - you can use:

```csharp
if (logger.IsEnabled(LogLevel.Debug))
{
   // Do the computation and log the result
}
```

HTH!~

**Comment by am11** [comment]
Sorry for not getting back earlier (it fell off my radar), but thanks for the suggested solution @nblumhardt. Cheers! 🌮 
I will create a tiny wrapper methods with the condition: "log or no-op" :)
