### ISSUE TITLE
HostingScope gets decomposed and not rendered in {Scope} format

### ISSUE THREAD

**Issue by pakrym** [serilog/serilog-extensions-logging#71]
When using Console logger with `includeScopes=true` all scopes gets rendered with a log message, I think users would expect similar behavior from `{Scope}` format, instead hostings scope state gets decomposed into properties and not logged as part from `{Scope}`.

Expected output:
```
2017-02-15 15:28:34 [Information] ["RequestId:0HL2LV9E249UM RequestPath:/", "Main", "Main2"] Waiting for user input
```

Actual output:
```
2017-02-15 15:28:34 [Information] ["Main", "Main2"] Waiting for user input
```

Repro code:

```
using System;
using System.IO;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Serilog;

namespace LogScopeOnAzure
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

            host.Run();
        }
    }

    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            var loggers = new Serilog.LoggerConfiguration().WriteTo.Console(outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss} [{Level}] {Scope} {Message}{NewLine}{Exception}");
            loggerFactory.AddSerilog(loggers.CreateLogger());
            loggerFactory.AddConsole(true);

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.Run(async (context) =>
            {
                var logger = context.RequestServices.GetService<ILogger<Startup>>();
                logger.LogCritical(1, "Unexpected critical error starting application");
                logger.LogError(1, "Unexpected error");
                logger.LogWarning(1, "Unexpected warning");


                using (logger.BeginScope("Main"))
                using (logger.BeginScope("Main2"))
                {

                    logger.LogInformation("Waiting for user input");
                    
                    logger.LogInformation("User typed '{input}' on the command line", "Inpuit");
                    logger.LogWarning("The time is now {Time}, it's getting late!", DateTimeOffset.Now);
                    await context.Response.WriteAsync("Hello World!");
                }
            });
        }
    }
}
```

**Comment by nblumhardt** [comment]
That's interesting - thanks for the info.

For file output this makes sense; for other back-ends having properties like `RequestId` at the top level is a more useful.

There's nothing to prevent us having both: pushing the scope object onto the stack _and_ decomposing it, so you'd get:

```
2017-02-15 15:28:34 [Information] [{RequestId: "0HL2LV9E249UM", RequestPath: "/"}, "Main", "Main2"] Waiting for user input
```

(Or something pretty similar, if we use the formatter to convert the value into its string form.)

The down-side would be the extra weight in the `Scope` payload, duplicating info we've already attached to the event. In some situations I can see this making a pretty substantial impact on event size, it's not unusual to have quite a lot of scope data:

![image](https://cloud.githubusercontent.com/assets/342712/23005851/2e930e18-f44a-11e6-883f-5e1759fc618f.png)

Not all properties above are coming in via `BeginScope()`, but a lot are (`ActionId`, `ActionName`, ...) and I don't know how usable this would be when rendered out into a log file. _Serilog.Extensions.Logging.File_ gets around this by picking a few key properties like `RequestId` and giving them special treatment.

The current scheme manages to preserve all of the available information fairly efficiently. FWIW, I wrote up the scheme we're using a little while ago - https://nblumhardt.com/2016/11/ilogger-beginscope/ - I don't think there's much more detail in that post than you already have, though.

Thoughts?

**Comment by pakrym** [comment]
@nblumhardt  what if we only add `.ToString()` representation of scope value to `Scope` property?

**Comment by nblumhardt** [comment]
@pakrym I don't think it would make much difference - the text wo

**Comment by nblumhardt** [comment]
_(Keyboard fumble..)_

The text would still be long, and the amount of data attached to the event would be similar. That `ActionName` property for example would still push the rest of the event information far out into the right column.

How does the console provider end up looking when scope gets heavy use? Is it still readable? I haven't had  any experience with the built-in providers yet, personally.

**Comment by nblumhardt** [comment]
Now that it's possible to include `{Properties}` in Serilog console output templates, I think this is a reasonable alternative to including everything in the rendering of `{Scope}`; although it's a strong suggestion, I don't think we're likely to tackle this in the near future. Thanks @pakrym !

**Comment by wzuqui** [comment]
In my case, I had to make a easy.

Here's the code on github:
https://github.com/wzuqui/Serilog.Enrichers.ActionName/blob/master/ActionName.cs
