### ISSUE TITLE
Formatter is not always called, by Log method

### ISSUE THREAD

**Issue by JohnRusk** [serilog/serilog-extensions-logging#77]
I'm passing a modified "formatter"  function into the Log method.  However, its not getting called. The reason appears to be that "state is IEnumerable<KeyValuePair<string, object>>== true", and in that code path, there seem to be cases where formatter is not called.   Is that by design, or a bug?

**Comment by nblumhardt** [comment]
Hi John, thanks for the note. Can you please post a snippet of the logging method call, and a sketch of the output you'd expect? Thanks!

**Comment by JohnRusk** [comment]
I made a wrapper around the Microsoft ILogger, which I'm calling PrefixedLogger. See code below.

So if I do this:
`var p = new PrefixedLogger(existingILogger, "foo ");
p.LogInformation("bar");`

I would expect the output, to the LiterateConsole, to look like:

[13:41:00 INF] foo bar

Effectively I'm trying to simulate a poor-man's version of Serilog's ".ForContext", while keeping my application code dependent only on the Microsoft.Extensions.Logging.ILogger interface. (That means I can't call ForContext directly.)

Breakpoints on the following confirm that augmentedFormatter is never called:

`
     /// <summary>
    /// Wraps an <see cref="ILogger"/> and prefixes all output with a fixed string
    /// </summary>
    public class PrefixedLogger: Microsoft.Extensions.Logging.ILogger
    {
        private readonly ILogger _innerLogger;
        private readonly string _prefix;

        public PrefixedLogger(ILogger innerLogger, string prefix)
        {
            _innerLogger = innerLogger;
            _prefix = prefix;
        }

        public IDisposable BeginScope<TState>(TState state)
        {
            return _innerLogger.BeginScope(state);
        }

        public bool IsEnabled(LogLevel logLevel)
        {
            return _innerLogger.IsEnabled(logLevel);
        }


        public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception,Func<TState, Exception, string> formatter)
        {
            // construct a formatter that adds our desired prefix to everything 
            Func<TState, Exception, string> augmentedFormatter = (s,e) => _prefix + formatter(s, e);

            _innerLogger.Log(logLevel, eventId, state, exception, augmentedFormatter);
        }

    }`

**Comment by nblumhardt** [comment]
Hi @JohnRusk - sorry about the quiet on this one, with custom wrapper code it's hard to tell what's going on at a glance, and thus a bit tricky to make any useful suggestions.

If you still need a hand with this, or think there's a bug in the provider, please do let us know and we'll reopen. Thanks!

**Comment by rileyFoster1989** [comment]
Hello @JohnRusk , I am currently having the same issue. Was there ever a resolution to your problem?

**Comment by JohnRusk** [comment]
I just stopped relying on the formatter object, and did my own string
concatenation. Fortunately my case was simple enough for that to be
practical.

John

**Comment by rileyFoster1989** [comment]
thank you for the response
