### ISSUE TITLE
How to disable Entity Framework Core SQL Queries logging?

### ISSUE THREAD

**Issue by SuddenGunter** [serilog/serilog-extensions-logging#78]
I've Asp.Net Core project with Serilog and Serilog extensions logging. And I want to disable all SQL queries, that EF Core logs in information level. I've found [this article](https://docs.microsoft.com/en-us/ef/core/miscellaneous/logging), but it says to filter logs by category - and I haven't found an ability to do so in Serilog. 
```
//Config in Startup.cs:
//Startup constructor:
            Log.Logger = new LoggerConfiguration()
               .MinimumLevel.Information()
               .WriteTo.RollingFile(pathFormat: Path.Combine(Configuration.GetSection("SerilogPath").Value, "log-{Date}.txt"), fileSizeLimitBytes: 100000, retainedFileCountLimit: 1)
               .CreateLogger();
//Configure method:
            loggerFactory.AddSerilog();
            appLifetime.ApplicationStopped.Register(Log.CloseAndFlush);

```

**Comment by adamchester** [comment]
Hi @SuddenGunter, try using `MinimumLevel.Override`

```csharp 
Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Verbose()
    .MinimumLevel.Override("Microsoft", LogEventLevel.Warning)
    .WriteTo.Sink(new MyFancySink())
    .CreateLogger();
```

**Comment by SuddenGunter** [comment]
@adamchester thank you, it works!

**Comment by apis3445** [comment]
Hi! I want to query the entity frameworks querys but I don't find anything, I have your code but doesn't log the querys

**Comment by RehanSaeed** [comment]
I'm also getting no logs from Entity Framework Core. I've recently realized that this is the case since upgrading ASP.NET Core and EF Core to 2.0.

**Comment by nblumhardt** [comment]
@RehanSaeed @apis3445 have you switched to using https://github.com/serilog/serilog-aspnetcore for 2.0? This addresses some leveling issues. If so, and there are still problems, would you please raise a new issue over in that repository for the missing EF logs? This ticket's addressing a different issue. Thanks!

**Comment by RehanSaeed** [comment]
Looks like this is the issue: https://github.com/serilog/serilog-aspnetcore/issues/10. Unbelievable!

**Comment by umair-syed-webjet** [comment]
@adamchester what if we dont want to set minimum levels in the code and we want to keep them in the config files?

**Comment by cpirie** [comment]
@umair-syed-webjet found an example here: [https://stackoverflow.com/a/46204891/1558855](https://stackoverflow.com/a/46204891/1558855)
