### ISSUE TITLE
Cannot load assembly "Microsoft.Extensions.Logging.Abstractions" on full framework

### ISSUE THREAD

**Issue by sm-g** [serilog/serilog-extensions-logging#79]
.net 4.6.1 WCF service, with 
```
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
```
and    

```
    <PackageReference Include="Microsoft.Extensions.Logging">
          <Version>1.1.1</Version>
    </PackageReference>
    <PackageReference Include="Serilog.Extensions.Logging">
          <Version>1.4.0</Version>
    </PackageReference>
```

WcfService.dll.config in output contains 
```
    <runtime>
        <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
          <dependentAssembly>
            <assemblyIdentity name="Microsoft.Extensions.Logging.Abstractions" publicKeyToken="adb9793829ddae60" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-1.1.1.0" newVersion="1.1.1.0" />
          </dependentAssembly>
        </assemblyBinding>
        <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
          <dependentAssembly>
            <assemblyIdentity name="System.Security.Cryptography.X509Certificates" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
            <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
          </dependentAssembly>
        </assemblyBinding>
      </runtime>
```

Microsoft.Extensions.Logging.Abstractions.dll in output has version 1.1.1.

In runtime I got `Could not load file or assembly ' Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. ` (note - version is 1.0.0)

After removing Microsoft.Extensions.Logging package, only 1.0.0-trm-21431 version of Microsoft.Extensions.Logging.Abstractions.dll is in output. After removing Serilog.Extensions.Logging package, no Microsoft.Extensions.Logging.Abstractions.dll.

For .net Core console/web app same packages combintaion works.

**Comment by skomis-mm** [comment]
@sm-g , try put 
```xml
<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
```
to end point project (such as `WcfService.Host`) or put `<runtime>` section with binding redirects to its app.config (so they would appear in `WcfService.Host.exe.config`)

**Comment by sm-g** [comment]
I'm using IIS express to launch my service. What is "end point project" in my case?

**Comment by skomis-mm** [comment]
Then it should be a web project and accompanying web.config

**Comment by sm-g** [comment]
Are what you speaking about is already in opening post?

**Comment by nblumhardt** [comment]
Hi @sm-g; just to elaborate on the answer from @skomis-mm - is the redirect making it into a config file that the runtime is actually loading?

Most of the time, config files for individual assemblies like _WcfService.dll.config_ won't be picked up at runtime. It'll need to be in an app (.EXE) or web config file.

HTH,
Nick

**Comment by sm-g** [comment]
> is the redirect making it into a config file that the runtime is actually loading?

I hope yes, it is dll.config created from web.config in basic WCF project, hosted in IIS. Connection string and endpoint settings somehow used.

**Comment by nblumhardt** [comment]
Is it possible copying the binding redirects into Web.config might get them applied?

**Comment by sm-g** [comment]
Yes, that helps. 
It was my misunderstanding of WCF deployment.
