### ISSUE TITLE
Make function ConvertLevel public availabe so we can use it in our code

### ISSUE THREAD

**Issue by xrkolovos** [serilog/serilog-extensions-logging#81]
Make function ConvertLevel public availabe so we can use it in our code

**Comment by nblumhardt** [comment]
Thanks for the note @xrkolovos - what scenario would you use it in?

Regards,
Nick

**Comment by nblumhardt** [comment]
Closing for now as I think we might prefer to avoid adding more surface area to this library, but keen to collect any scenario info/feedback on this so feel free to add further comments here.

**Comment by xrkolovos** [comment]
I wanted to use it in my code, i just copied the function. I thing is usefull and it is kind in the spirit of this package.
It's your call.

**Comment by sanderd** [comment]
Needed it, copied it, but would also like it to be exposed instead.

Use-case:
Company nuget library that depends on a serilog sink, but its surface area is .NET Core logging.

**Comment by nblumhardt** [comment]
Perhaps we should take another look at this. Thanks for the feedback :-)
