### ISSUE TITLE
Logging to different files, dynamically change log file path or level.

### ISSUE THREAD

**Issue by Patryx** [serilog/serilog-extensions-logging#82]
Hi!
I have few questions about Serilog (with Microsoft.Extensions.Logging).
1) I cannot find any solution how to create different loggers which log messages to different files defined in configuration file (json). How to create such a mechanism? In .net for example log4net has such obvious possibility. How to do it and configure Serilog with Microsoft.Extensions.Logging.
2) I want to log data in different projects, each project with different log template, log file. How to do it? Everywhere there are only examples how to do it in main app library, but I just want to create a seperate DLL with logic which could be shared among different apps.
3) How to change log file, log level at runtime using file? It is such a basic feature and I cannot find any information how to achieve it in serilog.

**Comment by nblumhardt** [comment]
Hi @Patryx, thanks for the note.

1. [Serilog.Sinks.Map](https://github.com/serilog/serilog-sinks-map) might help with this, but there's no JSON config support I'm aware of.
2. Can you create a function like `MySharedType.ConfigureLogging(template)` that sets the static `Log.Logger`? Should be pretty straightforward to just write regular library code for this.
3. Check out https://nblumhardt.com/2014/10/dynamically-changing-the-serilog-level/

HTH!

**Comment by nblumhardt** [comment]
Closing as this isn't something we can resolve as an issue, but please jump in if you need further help. Thanks!

**Comment by Darshanphapale** [comment]
Hi,

I am having feature of Dynamically changing log file path.But when I am changing the path which is configurable,it writes partial log at  both places i.e. Old as well as New Path.Changing log file path should work without any service restart.How we can archive that?

**Comment by bartelink** [comment]
@Darshanphapale Best to ask this on stackoverflow.com tagged with `serilog` and show some code examples as to what you're doing right now
