### ISSUE TITLE
.NET 4.7 library is in netstandard2.0 folder

### ISSUE THREAD

**Issue by MichaelSL** [serilog/serilog-extensions-logging#86]
I'm using the dev build of Serilog.Extensions.Logging and it turned out that .NET 4.7 assembly supplied instead of netstandard 2.0.

![image](https://user-images.githubusercontent.com/2205113/28381338-c9945424-6cba-11e7-862e-d4d6d2a74255.png)

**Comment by nblumhardt** [comment]
That's very strange - here's the CSPROJ: https://github.com/serilog/serilog-extensions-logging/blob/dev/src/Serilog.Extensions.Logging/Serilog.Extensions.Logging.csproj#L7

I wonder if it could be a glitch in the viewer, rather than the package? Might need to unzip the NUPKG and dig around.

Is the assembly working correctly?

**Comment by MichaelSL** [comment]
The assembly is not working because netstandard uses `ILoggerFactory` and NET framework uses `ILoggingBuilder`

I had to add logger manually:
`factory.AddProvider((ILoggerProvider) new SerilogLoggerProvider(null, false));`

**Comment by MichaelSL** [comment]
Target framework is ok when using other viewer (Telerik)
![image](https://user-images.githubusercontent.com/2205113/28390783-c3e1007e-6cdb-11e7-9f2a-03971a83c4ea.png)

but the code is still wrong:
![image](https://user-images.githubusercontent.com/2205113/28390818-e3bd3eb2-6cdb-11e7-8e64-9738402da2cd.png)

**Comment by nblumhardt** [comment]
Is it possible you need to update Microsoft.Extensions.Logging? See e.g. https://github.com/serilog/serilog-extensions-logging/pull/83#pullrequestreview-50346699

**Comment by MichaelSL** [comment]
Indeed the version from NuGet has the `ILoggingBuilder`. I use the latest `Microsoft.AspNetCore.All` but I didn't change the signature of `Configure` method.
`ILoggingBuilder` is not resolved if I change the signature.

I need to configure logging when building a host in this way:
```
public static IWebHost BuildWebHost(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseStartup<Startup>()
                .ConfigureLogging(builder => builder.AddSerilog())
                .Build();
```

Could you confirm this?

**Comment by nblumhardt** [comment]
LGTM, though I'm just wrapping my head around the new APIs, too.
