### ISSUE TITLE
AddSerilog require a receiver ILoggingBuilder

### ISSUE THREAD

**Issue by michaelsogos** [serilog/serilog-extensions-logging#87]
I'm following github pages to get started with serilog; but visual studio show me the error in subject.

Seems that .AddSerilog() is not available for interface ILoggerFactory, but it is for ILoggingBuilder

I'm building in .NET Core 2

a snippet of what i'm doing
```
  public static void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            var applicationLifetime = app.ApplicationServices.GetRequiredService<IApplicationLifetime>();
            applicationLifetime.ApplicationStopping.Register(OnShutdown);
            
            loggerFactory.AddSerilog();
        }
```

**Comment by michaelsogos** [comment]
I found that the issue is on NuGet release 2.0.0 both 10169 and 10164.
Now I'm using 1.4.0 (as latest stable release) and the error disappear.

**Comment by michaelsogos** [comment]
Let me know when you will correct this issue :)

Great job guys! :)

**Comment by nblumhardt** [comment]
Hi Michael,

In the 2.x versions on NuGet, `AddSerilog` is defined for both `ILoggerFactory` and `ILoggingBuilder`:

https://github.com/serilog/serilog-extensions-logging/blob/dev/src/Serilog.Extensions.Logging/SerilogLoggerFactoryExtensions.cs#L40

Could you paste in the compiler output? Thanks!

**Comment by michaelsogos** [comment]
I'd like but it is in italian :) so i guess not really understandable for you :)

However if you trust me, the error in english sounds like "There aren't methods (or extension methods) AddSerilog() defined for object ILoggerFactory, the most closer caller is ILoggingBuilder." from VS2017 Preview 6

**Comment by nblumhardt** [comment]
Thanks for the update :-)

Just to triple-check, do you get the same error if you change the call to:

```
Serilog.SerilogLoggerFactoryExtensions.AddSerilog(loggerFactory);
```

?

If so, this will need some more investigation - can't think of any reason why this wouldn't be picked up, unfortunately.

**Comment by michaelsogos** [comment]
About the previous error, even if it is in italian:

```
Errore	CS1929	'ILoggerFactory' non contiene una definizione per 'AddSerilog' e il miglior overload 'SerilogLoggingBuilderExtensions.AddSerilog(ILoggingBuilder, ILogger, bool)' del metodo di estensione richiede un ricevitore di tipo 'ILoggingBuilder'
```

About the test you asked me above unfortunately again an error, but at least a more clear reason
```
Errore	CS0234	Il tipo o il nome dello spazio dei nomi 'SerilogLoggerFactoryExtensions' non esiste nello spazio dei nomi 'Serilog'. Probabilmente manca un riferimento all'assembly.
```
Translated sounds like: "The type or namespace ''SerilogLoggerFactoryExtensions' doesn't exists in the namespace 'Serilog'. Probably an external assembly reference is missing.

Should you update a modifier in the extension class? Is it not-public maybe? :)

**Comment by michaelsogos** [comment]
I look at your code and also for me there aren't evident reason why it not work ;(

Did you tried to remove this line? [EditorBrowsable(EditorBrowsableState.Never)] 
I know it should not be a problem, but maybe ...

**Comment by michaelsogos** [comment]
However, till now, in .Net Core 2 Preview 2 + Serilog.Extensions.Logging **1.4.0** + Seq 4.1.17 + Docker for Windows 17+; i don't have issue.

So i can continue to work and i can tell you, the library is amazing :); the idea to having a perpetual instance of (Log.Logger) open to me a lot of scenario without doing nothing :)

Just a recommendation, by default DotNet Core LogLevel admit from Trace=0 to Critical = 5 (or None=6), but in my appsettings.json if i set MinimumLevel to Trace an exception will encountered, actually the acceptable minimum level is "Debug"

**Comment by vineus** [comment]
Getting the same error in serilog.extensions.logging 2.0.0, .Net Core 2 Preview 2

```
error CS1929: 'ILoggerFactory' does not contain a definition for 'AddSerilog' and the best extension method overload 'SerilogLoggingBuilderExtensions.AddSerilog(ILoggingBuilder, ILogger, bool)' requires a receiver of type 'ILoggingBuilder'
```

**Comment by nblumhardt** [comment]
Just found the issue in the CSPROJ:

https://github.com/serilog/serilog-extensions-logging/blob/dev/src/Serilog.Extensions.Logging/Serilog.Extensions.Logging.csproj#L53

Needs a fix, I should be able to take a look later today but any help appreciated in the meantime.

**Comment by Longfld** [comment]
Want to use serilog in .Net core 2.0 release version? see here
https://gist.github.com/Longfld/de7a5d67a8a6af8684c840e569d58f53
