### ISSUE TITLE
How to add CategoryName to output

### ISSUE THREAD

**Issue by leastprivilege** [serilog/serilog-extensions-logging#9]
By default Serilog does not output the CategoryName  e.g.:

`var logger = loggerFactory.CreateLogger("test");`

I tried a couple of templates - e.g.

`.WriteTo.Trace(outputTemplate: "{Timestamp} [{Level}] ({CategoryName:l}) {Message}{NewLine}{Exception}")`

but it does not work - any pointers?

thanks

**Comment by nblumhardt** [comment]
Hi Dominick,

I'm not sure we have any handling for this currently - I'm not actually sure how _CategoryName_ propagates through the logging pipeline to be honest.

Any insights here would be appreciated. Definitely sounds like something we should support, if it's native to _m.f.Logging_.

**Comment by leastprivilege** [comment]
Well - I don't know either. Need to look at their source code. Thought that's pretty fundamental.

In LibLog I always used {Name} in the format string.

**Comment by leastprivilege** [comment]
Could someone help out? @danroth27 @haok @rynowak

**Comment by rynowak** [comment]
@nblumhardt - the category name is what's passed in here: https://github.com/serilog/serilog-framework-logging/blob/dev/src/Serilog.Framework.Logging/SerilogLoggerProvider.cs#L31

**Comment by nblumhardt** [comment]
Thanks @rynowak.

It looks like we should attach the `CurrentScope`'s name as a property, if there is one, in here:

https://github.com/serilog/serilog-framework-logging/blob/dev/src/Serilog.Framework.Logging/SerilogLoggerProvider.cs#L41

@leastprivilege how is the scope name actually set, when calling an `ILogger`? I don't seem to have a `BeginScope()` method that allows it to be provided...

**Comment by nblumhardt** [comment]
@leastprivilege sorry, I see that is in your original post. What I guess is throwing me off is how it fits with the hierarchical nature of the scopes, if it can only be set when creating the root logger? Cheers! :-)

**Comment by leastprivilege** [comment]
I remember seeing something about nested scopes in the source code. But for now I would be happy if the simple "name" would work ;)

**Comment by leastprivilege** [comment]
Was this ever resolved?

**Comment by nblumhardt** [comment]
No, not as yet - any help here would be great.

**Comment by prasannavl** [comment]
Not sure if it was updated since this question was asked, but categoryName is sent in as context in Serilog. 

So it should be available from `{SourceContext:l}` .. 

However, I'm wondering.. is there a way to conditionally emit it on the templates only if its available?
Doing something like
```
            config.WriteTo.ColoredConsole(outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss} [{Level}] [{SourceContext:l}] {Message}{NewLine}{Exception}");

```
ends up with the `[{SourceContext:l}]` when there is no SourceContext available.

**Comment by nblumhardt** [comment]
@prasannavl I think you need to omit the `:l` for the behaviour you're looking for (output template tokens are literals by default).

**Comment by prasannavl** [comment]
@nblumhardt, if I omit it, it ends up with quotes around it.

**Comment by prasannavl** [comment]
@nblumhardt - Actually, omitting `:l` doesn't help. It still ends up with the verbatim string - which I think is the correct behavior. I'm just wondering if there is a way to remove it when the property is not available.

**Comment by nblumhardt** [comment]
Interesting - are you using an old Serilog build? (Know that is unlikely - but the change to omit empty properties has been in there for a while, may be a bug here?)

**Comment by prasannavl** [comment]
Build info from `package.lock.json` : 
```
      "Serilog.Framework.Logging/1.0.0-rc1-final-10071": {
        "type": "package",
        "dependencies": {
          "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
          "Serilog": "1.5.11"
        },
```

**Comment by stajs** [comment]
> However, I'm wondering.. is there a way to conditionally emit it on the templates only if its available?

I'm also interested in this.

**Comment by nblumhardt** [comment]
Thanks for the notes and follow-ups.

This is a bug in `ColoredConsoleSink`: https://github.com/serilog/serilog/issues/649

The other sinks (Console, Literate Console) shouldn't have the issue. _Serilog.Sinks.LiterateConsole_ is by far my favourite console option now BTW, so worth trying out if you haven't already!

Hoping we'll get some traction on the issue linked above for 2.0 RTM (feel free to take a shot at it if you get an opportunity).

Thanks again!

**Comment by stajs** [comment]
> The other sinks (Console, Literate Console) shouldn't have the issue.

Tried it, much better! Thanks for the recommendation =)

**Comment by nblumhardt** [comment]
Looks like this is covered by `SourceContext`. Thanks again all!
