### ISSUE TITLE
About LoggerConfiguration

### ISSUE THREAD

**Issue by alonstar** [serilog/serilog-extensions-logging#94]
about Logging in ASP.NET Core 
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging?tabs=aspnetcore2x

the logging settings moved to Program.cs when Core 2.0.

		var host = new WebHostBuilder()
				.UseConfiguration(hostConfig)
				.UseKestrel()
				.UseIISIntegration()
				.UseContentRoot(Directory.GetCurrentDirectory())
				.ConfigureAppConfiguration((hostingContext, builder) =>
				{
					var env = hostingContext.HostingEnvironment;
					builder.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
						  .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true, reloadOnChange: true);
					builder.AddEnvironmentVariables();

					builder.AddUserSecrets<Startup>();

					Log.Logger = new LoggerConfiguration()
					.ReadFrom.Configuration(builder.Build())
					.Enrich.FromLogContext()
					.CreateLogger();
				})
				.ConfigureLogging((factory) =>
				{
					factory.AddSerilog();
					factory.AddDebug();
				})
				.UseStartup<Startup>()
				.Build();

**Comment by nblumhardt** [comment]
Thanks for the note! It's also possible to do it in `Startup.ConfigureServices()` - not sure which is preferable. I just updated README.md this morning with the "services" version - what do you think?

**Comment by alonstar** [comment]
I don't know what's different between services.AddLogging & builder.ConfigureLogging, but I prefer to add it before webhost.run because I can add logger at StartUp ctor.

**Comment by neman** [comment]
You could add loging in Program.cs, even before NET Core 2.0, but now it's much simpler and better API.

Here is example how you could achieve it before 2.0 https://github.com/neman/Logging-Course/blob/master/02%20ASP.NET%20Core%20Logger%20Factory%20Injection/LoggerFactoryInProgramMain/Program.cs#L28

**Comment by alonstar** [comment]
ohoh, thanks for your information.

**Comment by nblumhardt** [comment]
Thanks for the example, @neman. If it'd be better to show a `Program.cs` example, let me know. Otherwise, thinking what we have is a good starting point for most. Cheers!

**Comment by neman** [comment]
Maybe a wiki section for various configuration options?
