### ISSUE TITLE
asp-net core 2 release version

### ISSUE THREAD

**Issue by Longfld** [serilog/serilog-extensions-logging#95]
Hi Guys
Could you please help of asp.net core 2 release version upgrade?
Thanks!
https://blogs.msdn.microsoft.com/webdev/2017/08/14/announcing-asp-net-core-2-0/
And here 
https://docs.microsoft.com/en-au/aspnet/core/fundamentals/logging?tabs=aspnetcore2x

**Comment by nblumhardt** [comment]
Hi - this was published a few days ago: https://www.nuget.org/packages/serilog.extensions.logging - please let us know if you're having trouble with the new package version. Thanks!

**Comment by Longfld** [comment]
Hi, - could you please create some sample code for asp.net core 2.00 release ?
As below for 2.00 preview only,  logging has been changed  2.00 release.
https://github.com/serilog/serilog-extensions-logging/tree/dev/samples/WebSample

**Comment by andymac4182** [comment]
@Longfld If you look at the readme it has the correct code. https://github.com/serilog/serilog-extensions-logging/blob/dev/README.md

**Comment by Longfld** [comment]
Hi there, I have read your readme and it has only correct code for core 2
preview but dotnet core 2 , there is big changes between them just about
logging config. I am trying not to guess but get serilog right from your
guys.

**Comment by Longfld** [comment]
And my guess I need thing like below, to see whole solution check here
https://github.com/Longfld/ASPNETcoreAngularJWT

public static void Main(string[] args)
{
var webHost = new WebHostBuilder()
.UseKestrel()
.UseContentRoot(Directory.GetCurrentDirectory())
.ConfigureAppConfiguration((hostingContext, config) =>
{
var env = hostingContext.HostingEnvironment;
config.AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
.AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true,
reloadOnChange: true);
config.AddEnvironmentVariables();
//me add
Log.Logger = new LoggerConfiguration
().MinimumLevel.Error().WriteTo.RollingFile(Path.Combine(env.ContentRootPath,
"logs/{Date}.txt")).CreateLogger();
})
.ConfigureLogging((hostingContext, logging) =>
{
logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"
));
logging.AddSerilog(); //me add
logging.AddConsole();
logging.AddDebug();
})
.UseStartup<Startup>()
.Build();

webHost.Run();
}

**Comment by nblumhardt** [comment]
Thanks for the follow-up. There's more discussion going on in #98.
