### ISSUE TITLE
Two layers of log level filtering cause confusion :(

### ISSUE THREAD

**Issue by anurse** [serilog/serilog-extensions-logging#99]
As a newcomer to Serilog, but experienced with M.E.L, I was trying to add Serilog logging (in order to send log events to Elasticsearch). I wanted my minimum level to be `Trace` (in the M.E.L terminology), so I made sure my M.E.L filters were configured appropriately and wired everything up. My M.E.L.Console logger got the Trace messages fine, but Serilog didn't. I spun my wheels for a while before realizing that the [sample for configuring Serilog for M.E.L](https://github.com/serilog/serilog-extensions-logging#serilogextensionslogging--) leaves Serilog's Minimum Level set to `Information`, so the SerilogLoggerProvider was getting the `Trace` events, but filtering them out in it's own filter system.

If I'm using Serilog as a means to an end (i.e. I use M.E.L throughout my app to generate logs but want to use Serilog's Enrichers/Sinks/etc.), I really want to completely disable filtering at the Serilog level (or at least start with no filtering). Obviously that's not the right behavior if Serilog is my primary logging tool, so I understand why `LoggerConfiguration` sets the `MinimumLevel` to `Information` by default. Perhaps the Serilog.Extensions.Logging configuration patterns should use a slightly different entry point that can remove all the default filtering? At the very least, this is worth calling out in documentation.

**Comment by nblumhardt** [comment]
@anurse thanks for the post! This is a good perspective to add to the discussion on #98 (duplicate, I think).

**Comment by anurse** [comment]
Yeah, I had actually seen that one and semi-intentionally created a new one as I misinterpreted that issue as a more general .NET Core 2.0 support issue. But you're right, it is pretty well covered in there. I'll hop over to that thread and add any comments there.

Thanks!
